application: 'my-life-01'
runtime: java7
version: '4'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /likes
  script: unused
  login: optional
  secure: optional
- url: /login
  script: unused
  login: optional
  secure: optional
- url: /learn
  script: unused
  login: optional
  secure: optional
- url: /contact
  script: unused
  login: optional
  secure: optional
- url: /about
  script: unused
  login: optional
  secure: optional
- url: /css/cover\.css
  script: unused
  login: optional
  secure: optional
